step 1

In [1]:
!pip install google-search-results

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting google-search-results
  Downloading google_search_results-2.4.1.tar.gz (11 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from google-search-results) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->google-search-results) (2022.9.24)
Building wheels for collected packages: google-search-results
  Building wheel for google-search-results (setup.py) ... done
  Created wheel for google-search-results: filename=google_search_results-2.4.1-py3-none-any.whl size=25789 sha256=00897331e0e64dc762246acddd5569aa4537d51b44947dc8126597fabd26d4e6
  Stored in directory: /root/.cache/pip/wheels/82/a3/c5/364155118f298722dff2f79ae4dd7c91e92b433ad36d6f7e0e
Successfully built google-search-results
Installing collected packages: google-search-results
Successfully installed google-search-results-2.4.1

In [2]:
from serpapi import GoogleSearch
from urllib.parse import *

In [3]:
params = {
  "engine": "google_maps",
  "q": "martabak",
  "ll": "@-7.067187,110.4142924,15z",
  "type": "search",
  "api_key": "984597bbb75dfd9fa77a6eb29319100e569eb245556043b6713749827f887774"
}

search = GoogleSearch(params)

mPosition = 0 # Angka indeks dari data
mNums = 5 # Batas jumlah data yang ditampilkan
local_results = []

while mPosition <= mNums:
  results = search.get_dict()

  for result in results["local_results"]:
    mPosition += 1
    
    if mPosition <= mNums:
      
      # Jika jumlah review kurang dari 50, maka jangan masukkan datanya
      if result["reviews"] < 50:
        mNums += 1
        continue
        
      # Append data sesuai dengan batas jumlah yang sudah ditentukan
      local_results.append({'title': result["title"],
                           'data_id': result["data_id"],
                           'reviews_total': result["reviews"]});

  if "next" in results.get("serpapi_pagination", {}):
    # Akan mengubah parameter dari 'GoogleSearch()' dengan isi parameter dari halaman selanjutnya
    search.params_dict.update(dict(parse_qsl(urlsplit(results.get("serpapi_pagination").get("next")).query)))

  else:
    break

https://serpapi.com/search

In [4]:
data = {'restaurant_name':[],
        'name':[],
        'rating':[],
        'review':[]}

for lr in local_results:
  
  params = {
    "engine": "google_maps_reviews",
    "data_id": "",
    "api_key": "984597bbb75dfd9fa77a6eb29319100e569eb245556043b6713749827f887774"
  }
  
  params["data_id"] = lr['data_id']

  search = GoogleSearch(params)

  mPosition = 0 # Angka indeks dari data
  mNums = 50 # Batas jumlah data yang ditampilkan

  while mPosition <= mNums:
    results = search.get_dict()

    for result in results["reviews"]:
      mPosition += 1

      if mPosition <= mNums:
        # Append data sesuai dengan batas jumlah yang sudah ditentukan
        data['restaurant_name'].append(lr['title']);
        data['name'].append(result["user"]["name"]);
        data['rating'].append(result["rating"]);
        data['review'].append(result["snippet"]);

    if "next" in results.get("serpapi_pagination", {}):
      # Akan mengubah parameter dari 'GoogleSearch()' dengan isi parameter dari halaman selanjutnya
      search.params_dict.update(dict(parse_qsl(urlsplit(results.get("serpapi_pagination").get("next")).query)))

    else:
      break
    
review_original = data['review']

https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search

In [5]:
import pandas as pd
df_original = pd.DataFrame(data)
df_original.to_csv('review_tanpa_preprocessing.csv', index=False)

In [6]:
df_original

,restaurant_name,name,rating,review
0,Martabak Rizky Moro Sekaran,falakhul auliya,5.0,Yummy
1,Martabak Rizky Moro Sekaran,bahrudin yusuf,5.0,(Translated by Google) This is one of the deli...
2,Martabak Rizky Moro Sekaran,irkhamudin Pandhawa,5.0,(Translated by Google) Martabak egg and sweet ...
3,Martabak Rizky Moro Sekaran,A R,5.0,(Translated by Google) Sweet martabak and eggs...
4,Martabak Rizky Moro Sekaran,Sismono Gbs,5.0,(Translated by Google) Available at shopeefood...
...,...,...,...,...
245,Martabak dan Kue Bandung 7 Saudara,Pur Wono,5.0,
246,Martabak dan Kue Bandung 7 Saudara,Kaisar Akhmad,4.0,
247,Martabak dan Kue Bandung 7 Saudara,DARREL TOUR&TRAVEL,5.0,
248,Martabak dan Kue Bandung 7 Saudara,haryo bintang,5.0,
249,Martabak dan Kue Bandung 7 Saudara,Wikwik Ahh,5.0,